version: '3.9'

services:
    rabbitmq:
      image: rabbitmq:3-management-alpine
      restart: always
      container_name: 'rabbitmq'
      ports:
        - 5672:5672
        - 15672:15672
      volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    
    init_rabbitmq: 
      build:
        context: ./
        dockerfile: scripts/Dockerfile 
      depends_on:
        - rabbitmq