version: "3.9"

services:
  mysql:
    image: mysql:8.0
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root 
      MYSQL_DATABASE: mysqluser    
    volumes:
      - "mysql-data:/var/lib/mysql"    

volumes:
  mysql-data: